#!/usr/bin/env bash
# Regenerate the EPUB corpus from the sources it shares with the DOCX one,
# with pandoc. Requires pandoc 3.8.x on PATH; run from anywhere.
#
# As with `corpus/docx` and `corpus/odt`, this is pandoc's own output and
# proves only "ferrodoc reads what pandoc writes the way pandoc reads it".
# `corpus/epub-calibre` is what shows the reader handles a book pandoc did
# not author.
#
# `--split-level=1` is deliberate: a single-file EPUB exercises neither the
# spine nor the per-file identifier prefixing, which is most of what this
# reader does beyond the HTML one.
set -euo pipefail
cd "$(dirname "$0")"

src=../docx/src

for f in "$src"/*.md; do
    name=$(basename "$f" .md)
    (cd "$src" && pandoc "$name.md" --split-level=1 -o "$OLDPWD/$name.epub")
done
(cd "$src" && pandoc tables.html --split-level=1 -o "$OLDPWD/tables.epub")

for f in ../*.md; do
    name=$(basename "$f" .md)
    pandoc "$f" --split-level=1 -o "corpus-$name.epub"
done

# The spec chunks live in `corpus/epub-spec` and are generated by its own
# script. They are kept apart deliberately: each bundles 30 spec examples,
# so one of the HTML reader's 26 known divergences fails a whole document,
# and mixing them in here would report the HTML reader's fidelity under an
# EPUB gate's name.
